const DRAFT_BANNER = `> **DRAFT — must be reviewed.** This file was auto-generated by \`caf-initiator\`
> based on repo detection. Fill in the TODO sections before the team/agents use it.
`;

// Monorepo root scripts usually delegate to a task runner that fans out to every workspace, so
// an unscoped command here would run against apps unrelated to the ticket. The generator scopes
// its own output (utils/runner-command.js); this section is filled in by hand, so the same rule
// has to be stated in the generated text.
function verifyNote(isMonorepo) {
  if (!isMonorepo) {
    return (
      'Verify first that the script actually exists as a separate entry in `package.json` —\n' +
      'sometimes typecheck is "glued" into another script (e.g. `build: "tsc -p . && vite build"`),\n' +
      'not its own entry. If so, record it as a gap — don\'t write a command that doesn\'t exist.'
    );
  }
  return (
    'This is a monorepo: the command above MUST be scoped to the relevant workspace — never run\n' +
    'from the root. Root scripts usually delegate to a task runner that fans out to EVERY\n' +
    'workspace, so an unscoped gate can reformat/build apps unrelated to the ticket\n' +
    '(e.g. `eslint --fix` running on other apps too). Scoping syntax differs per package manager\n' +
    '(`pnpm --filter <package-name> run <script>`, `yarn workspace ...`, `npm run ... --workspace ...`) —\n' +
    'use the package name from the `name` field in that app\'s `package.json`, not the folder path.\n\n' +
    'Also verify the script actually exists as a separate entry in that app\'s `package.json` —\n' +
    'sometimes typecheck is "glued" into another script (e.g. `build: "tsc -p . && nest build"`),\n' +
    'not its own entry. If so, record it as a gap — don\'t write a command that doesn\'t exist.'
  );
}

export function buildClaudeMd({ isMonorepo, monorepoTool, packageManager, apps, database, tracker }) {
  const pm = packageManager || 'TODO: fill in package manager';
  const appList = apps
    .map((a) => `- \`${a.path}\` — ${a.framework || 'TODO: framework not detected'}`)
    .join('\n');

  const databaseLine =
    !database || database.length === 0
      ? 'TODO: fill in database'
      : database.length === 1
        ? `${database[0].type} (detected via ${database[0].source})`
        : database.map((d) => `\`${d.scope}\`: ${d.type} (via ${d.source})`).join(', ');

  return `# CLAUDE.md

${DRAFT_BANNER}
## Project

- Type: ${isMonorepo ? `monorepo${monorepoTool ? ` (${monorepoTool})` : ''}` : 'single app'}
- Package manager: ${pm}
- Tracker: ${tracker || 'TODO: fill in tracker'}
- Database: ${databaseLine}

## Apps

${appList || '- TODO: no app detected yet'}

## Code Conventions

TODO: fill in concrete code conventions (naming, folder structure, error handling
patterns, etc). Don't write generic things AI already knows — focus on decisions
specific to this project.

## Business Context

TODO: describe the business domain, who the users are, and important constraints
agents must understand before changing code.

## Verification Commands

TODO: fill in the actual commands from \`package.json\` (don't assume script names):
- typecheck: \`${pm} run TODO\`
- lint: \`${pm} run TODO\`
- test: \`${pm} run TODO\`
- build: \`${pm} run TODO\`

${verifyNote(isMonorepo)}

## References

- See \`AGENTS.md\` for cross-tool rules.
- See \`.caf/knowledge/golden-examples/\` for code references.
- See \`.caf/knowledge/decisions/\` for ADRs.
- See \`.caf/tasks/README.md\` for the artifact handoff structure.
`;
}
