// Companion slash command for keeping docs/feature-catalog.md in sync with the code. Same
// generation-time variant pattern as buildAuditToTicketMd() in audit-commands.js: the scan
// strategy is picked here, from the detected architecture, so the generated command carries
// exactly one strategy — the agent running it in the target repo never has to choose.

const DRAFT_BANNER =
  '> DRAFT generated by caf-initiator — review and complete before use, especially the\n' +
  '> sections marked TODO project-specific.';

const CATALOG_PATH = 'docs/feature-catalog.md';

function controllerBasedVariant() {
  return {
    contextNote:
      'This project was detected as **controller-based** (backend has `*.controller.ts`, frontend has\n' +
      'a router). Feature = intersection between backend endpoints and the frontend routes that consume them.',
    scanStep: `### 2. Scan the code — controller-based strategy

1. Collect all backend controllers:
   \`\`\`bash
   rg --files -g '**/*.controller.ts'
   \`\`\`
2. Group by module — module = the controller's parent folder name
   (e.g. \`src/modules/auth/auth.controller.ts\` → module \`auth\`). If the folder structure
   has no module level, use the controller basename without the suffix (\`auth.controller.ts\`
   → \`auth\`).
3. For each controller, read its decorators/handlers and record the list of endpoints
   (HTTP method + path).
4. Collect frontend routes from the router file(s) (e.g. \`router/index.ts\`, \`src/router/**\`).
   Record the route path + the component/page it targets.
5. **Capability = intersection of controller + route**: one feature entry per backend module
   that has a frontend route consuming it. Match by similar module/path names,
   then VERIFY by reading the frontend code (import of the service/composable/API call that
   calls that endpoint) — don't rely on name similarity alone.
6. If a backend module has NO frontend route (e.g. webhook, cron, internal API),
   still record it as a feature entry but mark it \`(backend-only)\` in the Route column.
   If a frontend route has NO backend controller (e.g. a static page), mark it
   \`(no backend)\` in the Endpoint column.`,
    entryFormat: `| Feature | Module | Endpoint | Frontend Route | Status |
| --- | --- | --- | --- | --- |
| Authentication | \`auth\` | \`POST /auth/login\`, \`POST /auth/refresh\` | \`/login\` | TODO |`,
  };
}

function dddLayerVariant() {
  return {
    contextNote:
      'This project was detected as **DDD-layer** (has `layers/<domain>/` with its own `pages/`).\n' +
      'One layer = one feature domain; capabilities are derived from the pages inside that domain.',
    scanStep: `### 2. Scan the code — DDD-layer strategy

1. Collect all domains:
   \`\`\`bash
   ls -d layers/*/
   \`\`\`
   One \`layers/<domain>/\` folder = one feature domain.
2. For each domain, collect its pages:
   \`\`\`bash
   rg --files layers/<domain>/pages
   \`\`\`
   Each file in \`pages/\` = one capability. Derive its route from the file path structure
   per the file-based routing convention (e.g. \`pages/index.vue\` → \`/\`,
   \`pages/detail/[id].vue\` → \`/detail/:id\`).
3. For each capability, read the page's contents and record the data source it uses
   (composable/store/server route being called). This is what distinguishes a real
   capability from a placeholder page.
4. A domain with \`layers/<domain>/\` but NO \`pages/\` is not a user-facing feature
   (usually a shared/config layer) — do NOT add it to the catalog.`,
    entryFormat: `| Feature | Domain | Capability (page) | Route | Status |
| --- | --- | --- | --- | --- |
| Article Management | \`layers/article\` | \`pages/index.vue\`, \`pages/[id].vue\` | \`/article\`, \`/article/:id\` | TODO |`,
  };
}

function unknownVariant() {
  return {
    contextNote:
      '**TODO — architecture pattern not detected when this command was generated.** The project\n' +
      'structure did not match the controller-based pattern (`*.controller.ts` + frontend router) or the\n' +
      'DDD-layer pattern (`layers/<domain>/pages/`).',
    scanStep: `### 2. Scan the code — strategy NOT YET DETERMINED

**TODO — complete this section before using the command.** Pick one:

- Re-run \`caf-init scaffold feature-catalog-sync\` once the project structure is clearer
  (e.g. after the first module/page is built), so the matching strategy variant is
  generated automatically.
- Or fill this in manually: where the feature list is read from (which folder/file pattern),
  how those files are grouped into a single feature, and where each feature's
  capabilities are derived from.

Until this TODO is filled in, do NOT run step 3 onward — the result would be a
guessed catalog, not one derived from the code.`,
    entryFormat: `| Feature | Code Location | Capability | Status |
| --- | --- | --- | --- |
| TODO | TODO | TODO | TODO |`,
  };
}

/**
 * feature-catalog-sync.md — architecture-specific (same Variant A/B/C pattern as
 * buildAuditToTicketMd in audit-commands.js). `architecture` is the value from
 * detectArchitecture (src/utils/architecture-signatures.js):
 * 'controller-based' | 'ddd-layer' | null.
 */
export function buildFeatureCatalogSyncMd({ architecture, agentDir = '.claude/agents' } = {}) {
  const variant =
    architecture === 'controller-based'
      ? controllerBasedVariant()
      : architecture === 'ddd-layer'
        ? dddLayerVariant()
        : unknownVariant();

  return `---
allowed-tools: Read, Write, Edit, Grep, Glob, Bash
description: Sync ${CATALOG_PATH} with the code — add new features, refresh TODO entries, flag missing ones. Never deletes human-written entries.
argument-hint: [optional: scope, e.g. "apps/api" or a specific module name]
---

${DRAFT_BANNER}

# Feature Catalog Sync

Sync \`${CATALOG_PATH}\` with the current state of the code.

${variant.contextNote}

If the Documentation agent exists at \`${agentDir}/caf-documentation.md\`, read and follow
the documentation-writing rules there as the primary source of truth for style and
structure — this command only governs *how the content is detected*.

## Arguments

\`$ARGUMENTS\` — optional, limit the scan to a specific scope (an app path or module/domain name).
If empty, scan the whole repo.

## Steps

### 1. Read the existing catalog

- Read \`${CATALOG_PATH}\`. If it doesn't exist yet, create it with the header and an empty table
  (format in step 3), then continue — all scan results become new entries.
- If it already exists, note for each entry: feature name, the code location it references, and
  whether its content is still \`TODO\` or already human-written. This classification is used
  in step 4 — don't skip it.

${variant.scanStep}

### 3. Entry format

The catalog uses a single table with the following columns:

\`\`\`markdown
${variant.entryFormat}
\`\`\`

Status column: \`TODO\` (generated, not yet human-verified), \`OK\` (already
verified), or \`⚠️ stale\` (see step 4).

### 4. Merge rules (IDEMPOTENCY — this is the most important part)

Compare the step 2 scan results against the catalog read in step 1:

- **Present in code, not yet in catalog** → APPEND a new entry at the end of the table with
  Status \`TODO\`. Don't insert it in the middle and don't reorder the table —
  the existing order may have been deliberately arranged by a human.
- **Present in code, already in catalog with Status \`TODO\`** → REFRESH: update the
  code location/capability columns per the latest scan. \`TODO\` entries belong to the
  generator and are safe to overwrite.
- **Present in code, already in catalog with human-written content** (Status \`OK\`, or a
  description that's clearly not generated) → DO NOT TOUCH at all. If the scan
  result differs from the entry's content, report the difference to the user in the final
  summary and let the user decide.
- **In the catalog, no longer in the code** → DO NOT DELETE. Mark the Status as
  \`⚠️ stale\` and add a brief note why (e.g. "module \`x\` no longer found
  in the code"). Deleting an entry is always a human decision.

### 5. Final summary

After writing, show a summary:

\`\`\`
Finished syncing ${CATALOG_PATH}:
- N new entries added (Status TODO): [list]
- M TODO entries refreshed: [list]
- K entries marked ⚠️ stale: [list + reason]
- L human-authored entries skipped: [list]
- Discrepancies needing a human decision: [list, or "none"]
\`\`\`

## Constraints (must not be violated)

- Do NOT delete any row from \`${CATALOG_PATH}\` — entries missing from the code
  are marked \`⚠️ stale\`, not deleted.
- Do NOT overwrite entries already written by a human, even if the scan result looks more
  accurate. Report it, don't fix it yourself.
- Do NOT reorder or reformat the existing table — only touch rows that actually changed.
- Do NOT modify any code file. This command only writes \`${CATALOG_PATH}\`.
- If the scan finds nothing, STOP and report — don't write an empty catalog
  that overwrites the previous content.
`;
}
