const DRAFT_BANNER = `> **DRAFT — empty placeholder.** This file was generated by \`caf-initiator\` because it was
> explicitly requested during scaffolding. This document is optional and read-only for CAF —
> it usually comes from the Product/Design team, not created automatically. Fill it in manually,
> or delete it if not relevant.
`;

export function buildPrdMd() {
  return `# PRD — Product Requirements Document

${DRAFT_BANNER}
## Summary

TODO: one paragraph on what this product/initiative is and why it's being built.

## Problem

TODO: the user/business problem this is meant to solve.

## Target Users

TODO: who uses this, which segment.

## Scope

TODO: what's included and not included in this release.

## Success Criteria

TODO: metrics or conditions that indicate this succeeded.

## References

TODO: links to design, research, or other supporting documents.
`;
}

export function buildFeatureSpecMd({ featureName }) {
  return `# Feature Spec — ${featureName}

${DRAFT_BANNER}
## Summary

TODO: one paragraph on what this feature is.

## Why

TODO: the problem/need driving this feature, link to \`docs/product/prd.md\` if relevant.

## Expected Behavior

TODO: the main flow/scenarios, including important edge cases.

## Out of Scope

TODO: what's deliberately excluded from this feature.

## Related Tickets

TODO: link manually to the ticket tracker once broken down.
`;
}

export function buildSystemOverviewMd() {
  return `# System Overview

${DRAFT_BANNER}
## Components

TODO: list of the main apps/services and their responsibilities.

## Data Flow

TODO: high-level picture of how data flows between components.

## External Dependencies

TODO: third-party services used (auth provider, payment, etc.).

## Diagram

TODO: link or paste an architecture diagram if available.
`;
}

export function buildApiContractMd() {
  return `# API Contract

${DRAFT_BANNER}
> Detected FE and BE as separate within one repo — this document is optional, used by the
> Architect Agent as an additional reference when available (see CAF.md Layer 2).

## General Conventions

TODO: base URL, response format, error conventions, auth header, etc.

## Endpoints

TODO: list of endpoints (or link to the OpenAPI/GraphQL schema if it already exists as the source
of truth, and make this file just a summary).
`;
}

export function buildErdMd() {
  return `# ERD — Entity Relationship

${DRAFT_BANNER}
> Complements the actual schema (e.g. \`prisma/schema.prisma\`), not a replacement — if the
> schema changes, update this document too.

## Entities

TODO: list of the main entities and their relationships.

## Diagram

TODO: link or paste an ERD diagram if available.
`;
}

export function buildTestingStrategyMd() {
  return `# Testing Strategy

${DRAFT_BANNER}
> Conventions & coverage targets — different from the per-ticket \`qa-report.md\` in \`.caf/tasks/{{TICKET-ID}}/\`.

## Test Types

TODO: unit / integration / e2e — which is required for what kind of change.

## Coverage Target

TODO: coverage target if any, or critical areas that must have tests.

## Conventions

TODO: naming, test file location, mocking policy, etc.
`;
}
