// `/caf-review` — companion command for the Reviewer Agent's INITIAL mode (CAF-PRREVIEW-01
// Checkpoint A, a separate sub-task from `/caf-fix-review`). Different from `fix-review-command.js`:
// that command RESPONDS to a human reviewer's comment on an already-opened PR (fix mode, reactive).
// This command is a full review from scratch for a PR that has NEVER been reviewed —
// commentContext is always empty, spawns caf-reviewer.md in the same mode as the usual pre-PR gate
// (not new logic in caf-reviewer.md itself — the mode is set via this command's spawn instructions).
//
// The GitHub endpoint used is COMPLETELY DIFFERENT from fix-review: this command POSTs to
// `pulls/{pr}/reviews` (an official PR Review — event APPROVE/REQUEST_CHANGES/COMMENT), not
// `pulls/{pr}/comments/{id}/replies` (a reply to an individual comment). Don't conflate the two.

const DRAFT_BANNER =
  '> DRAFT generated by caf-initiator — review and complete before using, especially the\n' +
  '> parts marked TODO project-specific.';

// Minimum tool scope for this command: Read/Grep/Glob to read `.caf/tasks/{TICKET-ID}/` artifacts
// (optional), Task to spawn caf-reviewer.md, `gh pr view`/`gh pr diff`/`gh repo view` for
// PR resolution, and `gh api` scoped per-endpoint (not a wildcard `gh api:*`) to the 3
// patterns actually called: `gh api user` (fetch username), `gh api repos/*/collaborators/*/
// permission` (permission check), `gh api repos/*/pulls/*/reviews` (GET existing + POST a new
// review — same endpoint, different method, so one pattern is enough). There is NO `Bash(git ...)`
// at all — this command never checks out/commits code, unlike `/caf-run-pipeline`.
const ALLOWED_TOOLS = [
  'Read',
  'Grep',
  'Glob',
  'Task',
  'Bash(gh pr view:*)',
  'Bash(gh pr list:*)',
  'Bash(gh pr diff:*)',
  'Bash(gh repo view:*)',
  'Bash(gh api user:*)',
  'Bash(gh api repos/*/collaborators/*/permission:*)',
  'Bash(gh api repos/*/pulls/*/reviews:*)',
].join(', ');

function roleLine(role, agentDir) {
  return `\`${role}\` (\`${agentDir}/${role}.md\`)`;
}

// Spawn prohibition SPECIFIC to this command — its contract differs from FIX_REVIEW_PROHIBITION in
// fix-review-command.js: that subagent writes fix-review-log.md (per-comment fixes), this
// subagent writes review-notes.md (full verdict, format already standardized in caf-reviewer.md/CAF.md
// Layer 3 — reused, not a new structure). Communication back to GitHub (POST pulls/reviews) is
// entirely the main thread's job in step 4, after the subagent finishes.
const REVIEW_PROHIBITION =
  'Do not `git push`, do not call `gh api` at all against GitHub, do not change ticket status ' +
  'in the tracker, do not fix any code — write `review-notes.md` only, in the usual format ' +
  '(Verdict, Security Audit, Qualitative Review, etc). Communicating back to GitHub (posting the ' +
  'PR Review) is the job of this command\'s main thread, done after you finish.';

// Permission threshold (write/maintain/admin) MUST stay in sync with the webhook side of
// caf-orchestrator (checkpoint CAF-PRREVIEW-01 Checkpoint B) AND with `/caf-fix-review` — single
// source of truth: `.ai/tasks/CAF-PRREVIEW-01/plan.md` §5. Changing the threshold here? Also check
// `fix-review-command.js` and confirm the orchestrator side is updated too — DO NOT update just one side.
const PERMISSION_THRESHOLD = ['write', 'maintain', 'admin'];

function permissionCheckSection() {
  return `## 0. Permission Check (REQUIRED, before any step below)

\`gh api repos/{owner}/{repo}/collaborators/{username}/permission --jq .permission\`

\`{username}\` is the user running this command — obtained from \`gh api user --jq .login\`.
Save this \`{username}\` result, it's reused in step 0.7 to check for an existing review.

Result is NOT one of \`${PERMISSION_THRESHOLD.join('\`, \`')}\` → **STOP, do not process
anything further.** NO error message to the user, NO review/comment to GitHub —
the command stops silently, only log internally if needed (e.g. one log line if there's a
mechanism for it) for an audit trail if necessary. This is not a bug, it's by design: the
CAF-PRREVIEW-01 whitelist trigger is deliberately designed to not leak to outside parties
that this command was ever invoked by an unauthorized user.

(This threshold refers to a single source: \`.ai/tasks/CAF-PRREVIEW-01/plan.md\` §5 — if the
threshold changes, update it there first, then here, in \`/caf-fix-review\`, AND on the
caf-orchestrator webhook side Checkpoint B. DO NOT update just one side.)`;
}

function prResolutionSection() {
  return `## 0.5 Resolve PR Number & TICKET-ID

The \`$ARGUMENTS\` argument is a **PR number** (e.g. \`81\`), **NOT a TICKET-ID** — consistent
with \`/caf-fix-review\`, don't mix them up.

**\`$ARGUMENTS\` is provided** → use it directly as the PR number, proceed to TICKET-ID
resolution below.

**\`$ARGUMENTS\` is empty** → auto-detect from the active branch (exact same pattern as
\`/caf-fix-review\` — reuse its logic, don't rewrite it differently):

\`\`\`
git branch --show-current
\`\`\`

- Matches pattern \`ai-agent/{TICKET-ID}\` → find its PR:
  \`\`\`
  gh pr list --head ai-agent/{TICKET-ID} --json number,url
  \`\`\`
  - Exactly one PR found → use its number, proceed.
  - No PR found for that branch → ask the user for the PR number directly, **STOP** until
    answered. Don't guess.
- Active branch does NOT match the \`ai-agent/*\` pattern → ask the user for the PR number
  directly, **STOP** until answered.

**TICKET-ID resolution** (needed for the \`.caf/tasks/{TICKET-ID}/\` path — see step 1),
is DERIVED from the PR already resolved above, **not detected separately again**:

\`\`\`
gh pr view {number} --json headRefName,baseRefName,url
\`\`\`

Parse the \`ai-agent/(.+)\` pattern from the resulting \`headRefName\` — this regex is THE SAME
as the one used by \`caf-orchestrator\` (\`AI_AGENT_BRANCH_PATTERN\` in \`run-pr-review.use-case.ts\`),
keep them in sync if either side changes.

- Matches → that's the TICKET-ID.
- The PR isn't from that branch pattern (a manual PR, not the result of \`/caf-run-pipeline\` or
  caf-orchestrator) → ask the user for the TICKET-ID manually, **STOP** until answered. Don't make
  up a TICKET-ID from a branch name with an unclear pattern.

Save the resolved \`{owner}\`, \`{repo}\` (from \`gh repo view --json owner,name\`),
\`{number}\`, \`{headRefName}\`, \`{baseRefName}\`, and \`{TICKET-ID}\` — used in all
subsequent steps.`;
}

function existingReviewSection() {
  return `## 0.7 Check for an Existing Review (idempotency)

This command can be invoked manually even if the PR has already been reviewed before (e.g. via
the \`caf-orchestrator\` webhook, or a previous \`/caf-review\` run) — check first so reviews
don't pile up without the user's knowledge.

\`\`\`
gh api repos/{owner}/{repo}/pulls/{number}/reviews
\`\`\`

Filter the result: look for an entry with \`user.login == {username}\` (the result resolved in
step 0 — the same user/token runs this command every time it's invoked).

- **Found a previous review from \`{username}\`** → show the user: timestamp
  (\`submitted_at\`), \`state\` (APPROVED/CHANGES_REQUESTED/COMMENTED), and the old review's
  \`html_url\`. Ask explicitly: proceed with a new review (piling up on the PR timeline), or
  cancel? Input other than yes/no → ask again, don't guess. User chooses cancel → **STOP**, no
  side effects after this.
- **Not found** (not yet reviewed by \`{username}\`) → proceed silently to step 1.

Reviews from OTHER actors (other human reviewers, other bots) don't count toward this
idempotency check — not relevant to deciding "has this command already run on this PR or not".`;
}

function readArtifactsSection() {
  return `## 1. Read Task Artifacts (optional, best-effort)

Additional context for the reviewer — path: \`.caf/tasks/{TICKET-ID}/\`:

- \`requirements.md\`
- \`design.md\`
- \`verify-report.md\`

Check each file with \`test -f\` (or read directly and catch not-found) before
assuming it exists. **Any missing folder or file → skip silently, DO NOT fail or STOP**
— a PR reviewed by this command isn't necessarily from the CAF pipeline (could be a manual PR),
so this artifact is purely optional.`;
}

function diffSection() {
  return `## 2. Fetch the PR Diff

\`\`\`
gh pr diff {number}
\`\`\`

Save the result (plus \`{headRefName}\`, \`{baseRefName}\` from the 0.5 resolution) as the main
context carried into the step 3 spawn — this is what's being reviewed, not the task artifact
from step 1 (that artifact is just additional context).`;
}

function spawnSection(agentDir) {
  return `## 3. Spawn ${roleLine('caf-reviewer', agentDir)} — INITIAL mode

The spawn prompt MUST include, verbatim:

> ${REVIEW_PROHIBITION}

In addition to the prohibition above, the prompt MUST include:
- **Explicit mode: INITIAL** — a FULL review of this PR's diff from scratch, using the same
  criteria & golden examples as the usual pre-PR review (security audit checklist, qualitative
  review, verdict APPROVE/CHANGES REQUESTED/DEFER — see \`${agentDir}/caf-reviewer.md\` for the
  full format). This is NOT the \`/caf-fix-review\` fix-comment mode — there's no human
  reviewer comment being responded to.
- \`commentContext = []\` (empty array, as-is — no comments to carry over, unlike
  \`/caf-fix-review\` which carries thread history).
- The TICKET-ID (resolved in 0.5 — don't re-detect it here).
- The PR diff from step 2, plus the task artifact from step 1 if present (leave that section
  empty in the prompt if it genuinely wasn't found, don't pretend it exists).
- Instructions to write \`.caf/tasks/{TICKET-ID}/review-notes.md\` — format EXACTLY as defined
  in \`${agentDir}/caf-reviewer.md\` (Ticket, Agent, Verdict, Security Audit, Qualitative Review,
  Verdict Rationale, For Developer) — **don't invent a new structure**, reuse the existing one.

Wait for the spawn to finish before proceeding to step 4.`;
}

function postReviewSection() {
  return `## 4. Post GitHub PR Review

Read \`.caf/tasks/{TICKET-ID}/review-notes.md\` from step 3. Take the \`Verdict\` from it,
map it to a GitHub PR Review \`event\` (this mapping is this command's own decision, NOT
defined in \`caf-reviewer.md\`):

| Verdict (review-notes.md) | GitHub \`event\` |
|---|---|
| APPROVE | \`APPROVE\` |
| CHANGES REQUESTED | \`REQUEST_CHANGES\` |
| DEFER | \`COMMENT\` |

A verdict OTHER than these three (e.g. \`NEEDS_HUMAN\` — that value is defined in
\`caf-reviewer.md\` for the pipeline's automatic retry cycle, NOT for this single-run manual
command) or capitalization/spelling that doesn't match exactly → **STOP**, show the raw
\`Verdict\` to the user, ask which GitHub event to use manually. Don't guess or default
silently to \`COMMENT\`.

\`body\` = a summary of \`review-notes.md\` (Verdict Rationale + a concise list of
Blockers/Non-blockers — not the entire raw file pasted in, but complete enough that a human
reviewer doesn't have to open the file to get the gist).

\`comments[]\` (optional) — if \`review-notes.md\` has findings with a specific \`path\`+\`line\`
that can be mapped to the PR diff (e.g. from a Security Audit section naming a specific file),
include them as per-file inline comments:

\`\`\`
gh api repos/{owner}/{repo}/pulls/{number}/reviews -X POST \\
  -f event="{APPROVE|REQUEST_CHANGES|COMMENT}" \\
  -f body="{summary}" \\
  -f 'comments[][path]=...' -f 'comments[][line]=...' -f 'comments[][body]=...'
\`\`\`

(or a JSON payload via \`--input -\` if there's more than one \`comments[]\` entry — pick
whichever approach is valid for multiple comments, don't assume there's only one.)

Findings without a clear \`path\`+\`line\` (general, qualitative concerns) → go into \`body\`
only, don't force them into an inline comment.

**If the \`gh api\` call above fails with \`422 Unprocessable Entity\`** — check the
\`errors[]\` field in the response:

- Contains \`"Can not approve your own pull request"\` (event \`APPROVE\`) OR
  \`"Can not request changes on your own pull request"\` (event \`REQUEST_CHANGES\`) — confirmed
  empirically (PR #83/GAN-114, 2026-08-22): the GitHub API rejects both of these events when the
  user running the command (the \`gh\` token) is the same as the PR author, with a different
  message per event, not one generic message. \`COMMENT\` is NOT subject to this restriction
  (confirmed to succeed when posting on your own PR). → **STOP, don't retry automatically with
  a different event.** Show the user: this PR is authored by the same user running the
  command — the GitHub API rejected \`{original event}\` for their own PR. Offer two explicit
  options, let the user choose (don't default to either):
  1. **Post as \`COMMENT\`** — \`body\` MUST start with an explicit statement of the actual
     verdict on the first line, e.g.: \`"⚠ Actual verdict: {APPROVE|REQUEST_CHANGES} — posted as
     COMMENT because the GitHub API rejected self-{approve|request-changes}."\`, followed by the
     usual summary. **Don't silently downgrade** — this statement must actually appear in the
     body that gets posted, not just be noted in a local log.
  2. **Cancel** — no PR Review gets posted. Suggest the user ask another reviewer/token to run
     the command.
- \`errors[]\` does NOT match either pattern above (some other cause — e.g. PR already
  closed/merged, malformed \`comments[]\`) → **STOP as usual**, show the raw error message to the
  user. Don't assume this is a self-review case.`;
}

function summarySection() {
  return `## 5. Summary to the User

Show in chat: the final Verdict, the GitHub event used, a link to the newly created PR Review
(from the step 4 \`gh api\` response), and the location of \`review-notes.md\` for full details.`;
}

/**
 * review-command.md — CAF-PRREVIEW-01, INITIAL mode (separate companion from `/caf-fix-review`).
 *
 * @param {object} opts
 * @param {string} opts.agentDir  relative path to the agent folder (e.g. `.claude/agents`)
 */
export function buildReviewMd({ agentDir = '.claude/agents' } = {}) {
  return `---
allowed-tools: ${ALLOWED_TOOLS}
description: Full review from scratch for a PR that hasn't been reviewed yet — spawns caf-reviewer.md in INITIAL mode, then posts the result as a GitHub PR Review
argument-hint: [PR-number, e.g. "81"]
---

${DRAFT_BANNER}

# Review (Initial, Pre-existing PR)

**THIS COMMAND CREATES A NEW PR REVIEW ON GITHUB.** Its side effect is real and public — a PR
Review (APPROVE/REQUEST_CHANGES/COMMENT) appears on someone else's PR timeline. This isn't a
read-only preview like \`/caf-review-ticket\` — only run it when you actually intend to review
this PR right now.

Purpose: the interactive path for the Reviewer Agent's INITIAL mode — reviewing from scratch a
PR that has never been reviewed by anyone (human or bot), distinct from \`/caf-fix-review\`
(reactive mode, responding to a human reviewer's comment on an ALREADY-reviewed PR) and distinct
from the ${roleLine('caf-reviewer', agentDir)} pre-PR gate (triggered automatically in the
pipeline, not manually post-PR).

${permissionCheckSection()}

${prResolutionSection()}

${existingReviewSection()}

${readArtifactsSection()}

${diffSection()}

${spawnSection(agentDir)}

${postReviewSection()}

${summarySection()}

## Constraints

- This command NEVER runs \`git push\`, NEVER checks out/commits code, NEVER changes ticket
  status in the tracker — the only writes are \`review-notes.md\` (subagent) and the new
  PR Review on GitHub (main thread, step 4).
- The idempotency check (step 0.7) ONLY detects a previous \`/caf-review\` run (whether from
  this command itself, from the same \`{username}\`). An INITIAL review from the
  \`caf-orchestrator\` webhook is **NOT detected** — currently the webhook posts the initial
  review as a single summary issue comment (\`RunPrReviewUseCase\` → \`postIssueComment\`), NOT as a
  PR Review object via \`pulls/{number}/reviews\` like this command does. Two different artifact
  contracts, so \`GET pulls/{number}/reviews\` will never find that webhook review,
  regardless of whose login is being searched for. See the separate backlog item at
  \`.ai/tasks/CAF-PRREVIEW-01/open-items.md\` (caf-initiator) — migrating the webhook's initial
  review to \`pulls/{number}/reviews\` (if approved) would simultaneously make this idempotency
  check automatically work across both paths, but that's a decision that touches
  \`caf-orchestrator\`, outside this command's scope.
- Inline \`comments[]\` (step 4) depends on \`review-notes.md\` naming an explicit
  \`path\`+\`line\` for its findings — if the reviewer only gives a general concern without a
  clear location, the review still gets posted but without an inline comment (it all goes into
  the \`body\` summary).
- This Checkpoint A (caf-initiator) isn't yet wired to an automatic webhook — this command is
  always triggered manually by the user. Automatic triggering for a new PR (e.g. fired on the
  \`opened\` event) is caf-orchestrator's scope, outside this command.
- This command CANNOT produce a PR Review with event \`APPROVE\` or \`REQUEST_CHANGES\`
  if the user running the command is the author of the PR being reviewed — this is a
  restriction from the GitHub API itself (confirmed empirically, PR #83/GAN-114, 2026-08-22:
  both are rejected with \`422\` and a different message per event), not a bug in this command.
  The available fallback (see step 4): post as \`COMMENT\` with the actual verdict stated
  explicitly on the first line of the \`body\`, or cancel entirely — the command never silently
  downgrades the event without user confirmation.
`;
}
