import { buildVerifyChecklist } from './agent-md.js';

// CAF skills (CAF-SKILLS-01) — `.claude/skills/<name>/SKILL.md`. Two audiences, one file format:
// a manual Claude Code session picks a skill up through its frontmatter `description`, and a CAF
// agent reads it through the `Read` pointers in its `## Skills` section (see buildSkillsSection
// in agent-md.js for why it is a pointer and not a `skills:` key or the `Skill` tool).
//
// Universal on purpose: no framework convention library ships here — that goes stale and is a
// guess about the target repo. Only `caf-verify` carries project data, and only what detection
// found.
//
// This file is the single source for the skill names, the kind → skills table, the DRAFT banner
// and the open-TODO predicate: skills.js (generate), agents.js (new agents) and check-drafts.js
// (verify) all import from here so they can never disagree.

export const SKILLS_DIR = '.claude/skills';

// Display/write order. Every name is `caf-`-prefixed so a generated skill can't collide with one
// the team wrote themselves.
export const SKILL_NAMES = ['caf-verify', 'caf-scope-discipline', 'caf-no-guess', 'caf-escalate', 'caf-piv'];

const IMPLEMENTATION_SKILLS = ['caf-verify', 'caf-scope-discipline', 'caf-no-guess', 'caf-escalate'];
const ARTIFACT_WRITER_SKILLS = ['caf-scope-discipline', 'caf-no-guess'];

// Which skills an agent of each kind points at. A kind that is absent gets none (auditor, devops,
// pm, ux-designer). `caf-piv` is absent everywhere on purpose: it tells the reader to wait for
// the user's go-ahead, which a headless agent run can never get.
// `caf-escalate` stays with the implementation kinds — qa/reviewer/planner have their own
// escalation contracts in Retry Logic/Constraints that caf-orchestrator parses.
export const SKILLS_BY_KIND = {
  frontend: IMPLEMENTATION_SKILLS,
  backend: IMPLEMENTATION_SKILLS,
  implementer: IMPLEMENTATION_SKILLS,
  implementation: IMPLEMENTATION_SKILLS,
  qa: ['caf-verify', 'caf-no-guess'],
  planner: ARTIFACT_WRITER_SKILLS,
  reviewer: ARTIFACT_WRITER_SKILLS,
  architect: ARTIFACT_WRITER_SKILLS,
  documentation: ARTIFACT_WRITER_SKILLS,
};

export function skillsForKind(kind) {
  return [...(SKILLS_BY_KIND[kind] || [])];
}

export function skillPath(name) {
  return `${SKILLS_DIR}/${name}/SKILL.md`;
}

// The second half of the banner, addressed to the agent itself. Real dispatch (AC-9) showed the
// DRAFT sentence alone was not enough: an implementation agent still applied a DRAFT skill in 3
// of 9 runs, and in 0 of 5 with this line. Verbatim — don't reword it. check-drafts also looks
// for this text to catch a banner that was only half removed.
export const SKILL_DRAFT_AGENT_NOTICE = 'Agents: this skill is NOT ready';
const SKILL_DRAFT_AGENT_LINE =
  `> ${SKILL_DRAFT_AGENT_NOTICE}. Do not apply any rule in this file; ignore it entirely until this banner is removed.`;

export const SKILL_DRAFT_BANNER =
  '> DRAFT generated by caf-initiator — NOT active. CAF agents skip this skill until every `TODO`\n' +
  '> line below is resolved and a human removes this banner.\n' +
  SKILL_DRAFT_AGENT_LINE;

// True when the agent-facing banner line is still in the file, wherever it sits.
export function hasSkillDraftAgentNotice(content) {
  return String(content)
    .split(/\r?\n/)
    .some((line) => line.includes(SKILL_DRAFT_AGENT_NOTICE));
}

// The banner is the one runtime gate (an agent is told to skip a skill that still starts with
// it), so it is matched as a blockquote line near the top — not as the bare word, which a
// finished skill may legitimately use in prose.
export function hasSkillDraftBanner(content) {
  return String(content)
    .split(/\r?\n/)
    .slice(0, 15)
    .some((line) => /^>\s*DRAFT\b/.test(line));
}

// An open TODO in a skill is a line that STARTS with `TODO`, after an optional list marker and
// checkbox (`- [ ] TODO: ...`). The word inside a sentence is not counted: caf-no-guess and
// caf-verify have to mention it, and counting those would report a finished skill as unfinished
// forever.
const OPEN_TODO_LINE = /^\s*(?:(?:[-*+]|\d+\.)\s+)?(?:\[[ xX]\]\s+)?TODO\b/;

export function countOpenSkillTodos(content) {
  return String(content)
    .split(/\r?\n/)
    .filter((line) => OPEN_TODO_LINE.test(line)).length;
}

function skillMd({ name, description, title, banner = false, body }) {
  return `---
name: ${name}
description: ${description}
---

# ${title}
${banner ? `\n${SKILL_DRAFT_BANNER}\n` : ''}
${body}
`;
}

/**
 * caf-verify — the only skill built from detection. `verifyApps` is the same shape
 * buildVerifyChecklist() takes for an agent's `## Verify Checklist`
 * (`{ scripts, packageManager, packageName, appPath }` per app), so the commands here and in the
 * agent definitions come out of one function. Sorted by path: detection does not guarantee an
 * order. A slot with no detected script renders as a `TODO` line, never a guessed command, and
 * makes the whole skill a DRAFT.
 */
export function buildVerifySkill({ mode = 'SINGLE_REPO', verifyApps = [] } = {}) {
  const sorted = [...verifyApps].sort((a, b) => String(a.appPath).localeCompare(String(b.appPath)));
  const checklist = buildVerifyChecklist(sorted);
  return skillMd({
    name: 'caf-verify',
    description:
      'Verification commands for this repo (lint, typecheck, test, build). Use before claiming any code change is done, and whenever asked to verify, test or check work.',
    title: 'Verify before you claim done',
    banner: countOpenSkillTodos(checklist) > 0,
    body: `Commands detected by caf-init from \`package.json\` (repo mode \`${mode}\`):

${checklist}

Rules:

- Run every command above that applies to what you changed. In a monorepo, only the workspace(s)
  you touched.
- Report what you actually ran and its real result. Never write "passes" for a command you did
  not run.
- A failing check is fixed in the code — never by skipping, disabling or weakening the check (no
  \`--no-verify\`, no deleted test, no loosened rule).
- A line marked \`TODO\` above means no such script was detected. Do not invent a command for it;
  say that check was not run.
- If your agent definition has its own Verify Checklist, that list wins. How to report the result
  (file name, status word) is defined by the agent definition, not here.`,
  });
}

export function buildScopeDisciplineSkill() {
  return skillMd({
    name: 'caf-scope-discipline',
    description:
      'Keep a change inside the scope of the task. Use for every code or document change in this repo, before editing a file, when tempted to refactor or fix something nearby, or when a task seems to need a file outside the assigned area.',
    title: 'Stay inside the scope',
    body: `1. Know your scope before the first edit. Running as a CAF agent: the Scope section of your agent
   definition. Otherwise: the files the task names.
2. Touch only what the task needs. No drive-by refactors, renames, reformatting or dependency
   bumps.
3. Something broken or ugly outside the task: write it down as a finding in your output. Do not
   fix it.
4. The task cannot be done without a file outside your scope: stop before editing that file and
   report which file and why. Do not widen the scope yourself.
5. Lockfiles, CI configuration, env and secret files: leave them alone unless the task explicitly
   requires the change.
6. Before you finish, list the files you changed and confirm each one belongs to the task.

If this conflicts with your agent definition, the agent definition wins.`,
  });
}

export function buildNoGuessSkill() {
  return skillMd({
    name: 'caf-no-guess',
    description:
      'Do not invent facts about this codebase. Use whenever you are about to state or rely on something you have not read in the repo, such as a file path, function or script name, API field, config value, convention or requirement.',
    title: 'Verify it or mark it — never guess',
    body: `1. A claim about the code needs evidence you read in this session. Cite it as
   \`path/to/file.ext:line\`.
2. Before you use a name (file, function, script, env var, endpoint, field), open it or search
   for it. Not found means it does not exist — say so.
3. A gap in the requirements (ambiguous ticket, missing acceptance criterion, business rule) is
   not yours to fill. Do not silently pick the "reasonable" default.
4. What you cannot verify becomes an explicit open item in the artifact you produce, written as
   \`TODO: <what is unknown, where you looked>\`, and is mentioned in your report. How to escalate
   it is defined by your agent definition; in a manual session, ask the user.
5. Label an inference as an inference ("inferred from X, not confirmed").
6. Never present the output of a command you did not run, or describe a file you did not open.

If this conflicts with your agent definition, the agent definition wins.`,
  });
}

export function buildEscalateSkill() {
  return skillMd({
    name: 'caf-escalate',
    description:
      'When and how to stop and hand a task back to a human. Use when verification keeps failing, the task is blocked, the plan no longer matches the code, or a decision is needed that is not yours to make.',
    title: 'Escalate instead of pushing through',
    body: `Stop and escalate when:

- the same verification still fails after the retry limit in your agent definition (3 when none is
  stated) — count the attempts, and do not retry the same fix;
- the task needs a change outside your scope, or contradicts the requirements, an ADR or a
  documented convention;
- it needs a human decision: product behaviour, security, a data migration or destructive
  operation, a new dependency, credentials;
- a required input is missing or contradicts another one.

How:

- Running as a CAF agent: follow the Retry Logic and Constraints sections of your agent
  definition exactly. They name the report file and the exact status word; this skill never
  changes either. Never end a run with only a question in chat — write the report.
- In a manual session: stop and tell the user.

What the escalation contains: each attempt and its actual error, what is blocking, the specific
decision you need, and the options if you see any.

Leave the working tree as it is. No stubs or disabled tests to make it look green, no commit or
push.

If this conflicts with your agent definition, the agent definition wins.`,
  });
}

// Manual sessions only — never mapped to an agent kind (see SKILLS_BY_KIND).
export function buildPivSkill() {
  return skillMd({
    name: 'caf-piv',
    description:
      'Plan-Implement-Verify workflow for manual coding sessions in this repo. Use when the user asks for a code change, bug fix, feature or refactor directly in chat, not through a CAF agent or the caf-orchestrator pipeline.',
    title: 'Plan, implement, verify (manual sessions)',
    body: `For an interactive session with a human only. CAF agents have their own Working Pattern — do not
apply this in an agent or headless run.

1. PLAN — read first: \`CLAUDE.md\`, \`AGENTS.md\`, the code involved, and \`.caf/knowledge/\` if it
   exists. State the goal, the files you will touch, how you will verify, and your open
   questions. Then stop and wait for the user's go-ahead. A trivial change the user already
   spelled out (a typo, a one-line fix) needs only a one-line plan.
2. IMPLEMENT — only what the plan says. If the plan turns out wrong, go back to PLAN and tell the
   user. Apply the \`caf-scope-discipline\` and \`caf-no-guess\` skills.
3. VERIFY — run the commands in the \`caf-verify\` skill and report the real results. The work is
   not done until verification ran, or you said explicitly what could not be run and why.

Do not commit or push unless the user asks.`,
  });
}

/**
 * Every skill file `caf-init scaffold skills` writes, in SKILL_NAMES order:
 * `[{ name, relPath, content, draft }]`. Pure — no filesystem, no clock.
 */
export function buildSkillFiles({ mode, verifyApps } = {}) {
  const builders = {
    'caf-verify': () => buildVerifySkill({ mode, verifyApps }),
    'caf-scope-discipline': buildScopeDisciplineSkill,
    'caf-no-guess': buildNoGuessSkill,
    'caf-escalate': buildEscalateSkill,
    'caf-piv': buildPivSkill,
  };
  return SKILL_NAMES.map((name) => {
    const content = builders[name]();
    return { name, relPath: skillPath(name), content, draft: hasSkillDraftBanner(content) };
  });
}
