const DRAFT_BANNER = `> **DRAFT — must be reviewed.** This file was auto-generated by \`caf-initiator\`.
`;

export function buildTasksReadme({ tracker }) {
  return `# .caf/tasks/

${DRAFT_BANNER}
Each ticket gets its own folder here. Agents hand off files to each other, not chat/memory.

Folder names follow the ticket key from the tracker (**${tracker || 'TODO: fill in tracker'}**),
consistent with the branch name \`ai-agent/{{TICKET-ID}}\`.

## Structure per Ticket

\`\`\`
.caf/tasks/{{TICKET-ID}}/
  requirements.md    ← Planner Agent: what's requested, acceptance criteria
  design.md          ← Architect Agent: technical approach (if needed)
  tasks.md           ← Planner Agent: concrete task breakdown
  verify-report.md   ← implementation agent: implementation + verify results
  qa-report.md       ← QA Agent: deep test results
  review-notes.md    ← Reviewer Agent: qualitative review results
\`\`\`

See \`CAF.md\` Layer 3 for the \`verify-report.md\` format and details on each artifact.
`;
}
